{% set name = "rich-click" %}
{% set version = "1.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ewels/rich-click/archive/v{{ version }}.tar.gz
  sha256: c86c0c2f19c285bde21d022027252202058460ef3e9404798b217acbda5732e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rich-click=rich_click.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
  run:
    - python >={{ python_min }}
    - rich >=10.7
    - click >=7,<9

test:
  imports:
    - rich_click
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - rich-click --help

about:
  home: https://github.com/ewels/rich-click
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Format click help output nicely with rich
  description: |
    Provides attractive help output from click,
    formatted with rich, with minimal customisation required.
  doc_url: https://github.com/ewels/rich-click
  dev_url: https://github.com/ewels/rich-click

extra:
  recipe-maintainers:
    - ewels
    - synapticarbors
