{% set name = "rich-click" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ewels/rich-click/archive/v{{ version }}.tar.gz
  sha256: 74e55790e230ede1d642017810cfde12940a5b831026addb2e82195949ca3359

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - rich-click=rich_click.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - rich >=10,<12
    - click >=7,<9

test:
  imports:
    - rich_click
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ewels/rich-click
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Format click help output nicely with rich'
  description: |
    Provides attractive help output from click,
    formatted with rich, with minimal customisation required.
  doc_url: https://github.com/ewels/rich-click
  dev_url: https://github.com/ewels/rich-click

extra:
  recipe-maintainers:
    - ewels
