schema_version: 1

context:
  name: rich-click
  version: 1.9.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ewels/rich-click/archive/v${{ version }}.tar.gz
  sha256: 46c3720a4581496568c1fb103e4812761e93e0ec9e218d43df33c5583788eaac

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - rich-click=rich_click.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=45
  run:
    - python >=${{ python_min }}
    - rich >=12.0
    - click >=8
    - typing_extensions >=4
    - if: win
      then:
      - __win
      - colorama
      else:
      - __unix


tests:
  - python:
      imports:
        - rich_click
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - rich-click --help

about:
  license: MIT
  license_file: LICENSE
  summary: Format click help output nicely with rich
  description: |
    Provides attractive help output from click,
    formatted with rich, with minimal customisation required.
  homepage: https://github.com/ewels/rich-click
  repository: https://github.com/ewels/rich-click
  documentation: https://github.com/ewels/rich-click

extra:
  recipe-maintainers:
    - ewels
    - synapticarbors
