schema_version: 1

context:
  name: rich-click
  version: "1.9.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ewels/rich-click/archive/v${{ version }}.tar.gz
  sha256: 6e453d08cdc179821d3f6c3f9368f2facc4390605cda29d5ba9d0f2a5176dda4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  python:
    entry_points:
      - rich-click=rich_click.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=45
  run:
    - python >=${{ python_min }}
    - rich >=12
    - click >=8
    - typing-extensions >=4
    - if: win
      then:
        - __win
        - colorama
    - if: unix
      then: __unix

tests:
  - python:
      imports:
        - rich_click
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - rich-click --help

about:
  license: MIT
  license_file: LICENSE
  summary: Format click help output nicely with rich
  description: |
    Provides attractive help output from click,
    formatted with rich, with minimal customisation required.
  homepage: https://github.com/ewels/rich-click
  repository: https://github.com/ewels/rich-click
  documentation: https://github.com/ewels/rich-click

extra:
  recipe-maintainers:
    - ewels
    - synapticarbors
